name: HIFITI-Auto-Checkin

on:
  workflow_dispatch:
  schedule:
    # UTC 
    - cron: "40 23 * * *"

jobs:
  checkin:
    name: Checkin
    runs-on: ubuntu-latest
    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: 安装依赖
        run: npm install sync-request

      - name: 执行签到
        shell: bash
        run: |
          node main.js
